spring:
  application:
    name: task-management

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test@example.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Application settings
app:
  security:
    jwt:
      secret: ${JWT_SECRET:AV3rYS3cur3AndL0ngS3cr3tK3yF0rJWTG3n3rat10nInTh1sAppl1cat10n}
      expiration: 86400000 # 24 hours in milliseconds

  notification:
    email:
      enabled: true
      from: noreply@taskmanagement.com

# Logging configuration
logging:
  level:
    com.taskmanagement: INFO
    org.springframework.modulith: DEBUG

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha